version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "Infrastructure"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-cyv155sxktaa"
s3_prefix = "Infrastructure"
region = "us-west-2"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "MainBranch=main"

